name: ShulkerSpawn
version: 1.0.2
main: org.mythicmc.shulkerspawn.ShulkerSpawn
api-version: 1.16
description: Respawnable shulkers
commands:
  shulkerspawn:
    description: ShulkerSpawn base command
    usage: /shulkerspawn (reload/set)
    permission: shulkerspawn.admin
permissions:
  shulkerspawn.*:
    default: op
    children:
      - shulkerspawn.admin
  shulkerspawn.admin:
    default: op
    description: permission for /shulkerspawn reload
